---

- name: Install packages for postfix
  ansible.builtin.apt:
    pkg: ['postfix']
    state: present

- name: Setup a sending only mail server via main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart postfix

- name: Install /etc/mailname
  ansible.builtin.copy:
    content: "{{ postfix_send_only_hostname }}{{ '\n' }}"
    dest: /etc/mailname
    owner: root
    group: root
    mode: '0644'
  tags:
    - mailname
    - hostname

- name: Configure /etc/aliases to forward root's email
  ansible.builtin.lineinfile:
    dest: /etc/aliases
    regexp: "^root:.*"
    line: "root:{{ postfix_send_only_postmaster_email }}"
  register: aliases
  changed_when: aliases.changed
  notify: Rebuild aliases
